services:
  - type: web
    name: convite-casamento
    env: go
    buildCommand: go build -o main main.go
    startCommand: ./main
    envVars:
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"

